export default {
  work: ['iconfont icon-icok',
    'iconfont icon-xinzeng',
    'iconfont icon-baocun-tianchong',
    'iconfont icon-sousuo-tianchong',
    'iconfont icon-update',
    'iconfont icon-shanchu',
    'iconfont icon-zuo',
    'iconfont icon-you',
    'iconfont icon-msnui-info'
  ],
  text: ['供应商','编辑','转到','附加','环境','系统','帮助'],
  cell: ['复制','粘贴','剪切','向上插入行','向下添加行','删除当前行'],
  table: ['iconfont icon-fuzhi',
    'iconfont icon-niantie',
    'iconfont icon-jianqie',
    'iconfont icon-charuhang',
    'iconfont icon-shanchu1',
  ],
}
