export default {
      '基本信息': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      '采购(或外协)参数': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      '状态控制': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      '销售数量控制': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      '生产相关参数': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      '库存有关参数': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      '装箱信息': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      '财务相关': [
        {
            key:'MaterialNumber',
            title:'物料编号',
            value:'1',
            isInput:true
        },
        {
            key:'Preset',
            title:'预设来源类型',
            value:'2',
            isInput:true
        },
        {
            key:'MaterialClass',
            title:'物料种类',
            value:'3',
            isInput:true
        },
        {
            key:'BarCode',
            title:'条形码',
            value:'4',
            isInput:true
        },
        {
            key:'MaterialName',
            title:'物料名称',
            value:'5',
            isInput:true
        },
        {
            key:'BatchNumber',
            title:'批号控制',
            value:'6',
            isInput:true
        },
        {
            key:'Standard_1',
            title:'规格1',
            value:'7',
            isInput:true
        },
        {
            key:'Standard_2',
            title:'规格2',
            value:'8',
            isInput:true
        },
        {
            key:'Unit',
            title:'库存单位',
            value:'9',
            isInput:true
        },
        {
            key:'Quantity',
            title:'库存数量小位数',
            value:'10',
            isInput:true
        }
      ],
      initInputData: {
        MaterialNumber: "",
        Preset: "",
        MaterialClass: "",
        BarCode: "",
        MaterialName: "",
        BatchNumber: "",
        Standard_1: "",
        Standard_2: "",
        Unit: "",
        Quantity: ""
      }
}