export default {
    data: [
      {
        addLayer: 'btn',
        layer: '10',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        task: 'pRIM',
        machine: 'Res:555103',
        setupTime: '',
        runTime: '',
        res: '',
      },
   /*     {
        addLayer: '2',
        layer: '2',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        task: 'pRIM',
        machine: 'Res:555103',
        setupTime: '',
        runTime: '',
        res: '',
      },
  {
        addLayer: 'btn',
        layer: '10',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        task: 'pRIM',
        machine: 'Res:555103',
        setupTime: '',
        runTime: '',
        res: '',
      },
         {
        addLayer: 'btn',
        layer: '10',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        task: 'pRIM',
        machine: 'Res:555103',
        setupTime: '',
        runTime: '',
        res: '',
      }, */
    /*   {
        addLayer: 'btn',
        layer: '10',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        task: 'pRIM',
        machine: 'Res:555103',
        setupTime: '',
        runTime: '',
        res: '',
      }, */
   
    ],
    // label 表头
    columns: [ 
      { label: '添加工序', prop: 'addLayer' },
      { label: '工序号', prop: 'layer' },
      { label: '工序', prop: 'process' },
      { label: '厚度', prop: 'thickness' },
      { label: '直径', prop: 'diameter' },
      { label: '重量', prop: 'weight' },
      { label: '价格', prop: 'cost'},
      { label: '工艺', prop: 'task'},
      { label: '设备', prop: 'machine'},
      { label: '预留1', prop: 'setupTime'},
      { label: '预留2', prop: 'runTime'},
      { label: '预留3', prop: 'res'}
    ]
  }