export default {
    data: [
      {
        addLayer: 'btn',
        layer: '10',
        select: 'select',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        op:'10',
        task: 'pRIM',
        machine: 'Res:555103',
        setuptime: 'setuptime',
        runtime: 'runtime',
        res_1: '',
        res_2: '',
        res_3: '',
        res_4: '',
      },
      {
        addLayer: 'btn',
        layer: '10',
        select: 'select',
        process: 'Position',
        thickness: 'Design',
        diameter: 'Description',
        weight: '5.950',
        cost: '16.19',
        op:'Description',
        task: 'pRIM',
        machine: 'Res:555103',
        setuptime: 'setuptime',
        runtime: 'runtime',
        res_1: '',
        res_2: '',
        res_3: 'Diameter',
        res_4: 'Quantity',
      },
      {
        addLayer: 'btn',
        layer: '10',
        select: 'select',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        op:'10',
        task: 'pRIM',
        machine: 'Res:555103',
        setuptime: 'setuptime',
        runtime: 'runtime',
        res_1: '',
        res_2: '',
        res_3: '',
        res_4: '',
      },
      {
        addLayer: 'btn',
        layer: '10',
        select: 'select',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        op:'10',
        task: 'pRIM',
        machine: 'Res:555103',
        setuptime: 'setuptime',
        runtime: 'runtime',
        res_1: '',
        res_2: '',
        res_3: '',
        res_4: '',
      },
      {
        addLayer: 'btn',
        layer: '10',
        select: 'select',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        op:'10',
        task: 'pRIM',
        machine: 'Res:555103',
        setuptime: 'setuptime',
        runtime: 'runtime',
        res_1: '',
        res_2: '',
        res_3: '',
        res_4: '',
      },
      {
        addLayer: 'btn',
        layer: '10',
        select: 'select',
        process: 'INSULATE',
        thickness: '0.010',
        diameter: '0.050',
        weight: '5.950',
        cost: '16.19',
        op:'10',
        task: 'pRIM',
        machine: 'Res:555103',
        setuptime: 'setuptime',
        runtime: 'runtime',
        res_1: '',
        res_2: '',
        res_3: '',
        res_4: '',
      }
  
   
    ],
    // label 表头
    columns: [ 
      { label: '1.添加工序', prop: 'addLayer' },
      { label: '2.工序号', prop: 'layer' },
      { label: '3.选择', prop: 'select' },
      { label: '4.工序', prop: 'process' },
      { label: '5.厚度', prop: 'thickness' },
      { label: '6.直径', prop: 'diameter' },
      { label: '7.重量', prop: 'weight' },
      { label: '8.价格', prop: 'cost'},
      { label: '9.Op.', prop: 'op' },
      { label: '10.工艺', prop: 'task'},
      { label: '11.设备', prop: 'machine'},
      { label: '12.启动时间', prop: 'setuptime'},
      { label: '13.运行时间', prop: 'runtime'},
      { label: '14.预留1', prop: 'res_1'},
      { label: '15.预留2', prop: 'res_2'},
      { label: '16.预留3', prop: 'res_3'},
      { label: '17.预留4', prop: 'res_4'}
    ]
  }